name : first
on: push
jobs:  
    job1:
        name: First job
        runs-on: ubuntu-latest
        steps:
        - name: Step one
          uses: actions/checkout@v2
        - name: Step two
          run: env | sort
        - name: Angular Github Actions
          uses: mayur-rawte/github-angular-actions@latest
        - name: Angular Problem Matchers
          uses: EdricChan03/angular-problem-matchers-action@v0.0.0
    job2:
        name: Second job
        runs-on: windows-latest
        steps:
        - name: Step one
          uses: actions/checkout@v2
        - name: Step two
          run: "Get-ChildItem Env: | Sort-Object Name"
        - name: Angular Github Actions
          uses: mayur-rawte/github-angular-actions@latest
        - name: Angular Problem Matchers
          uses: EdricChan03/angular-problem-matchers-action@v0.0.0
